[package]
name = "webgl-rc-macro"
version = "0.1.2"
authors = ["Andrei Monkin <monkin.andrey@gmail.com>"]
repository = "https://github.com/monkin/webgl-rc"
description = "GLSL loading macro for webgl-rc"
license = "MIT"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
regex = "1.5.6"
